### ISSUE TITLE
Backslashes do not work in Linux

### ISSUE THREAD

**Issue by PKeidel** [Stwend/MeshroomTools#4]
On Linux it should be a "/" instead of a "\\".

Line 12+13
https://github.com/Stwend/MeshroomTools/blob/827a86f0e34bcfe2bcf1ea7b64524fc3050d530c/importing/ops/Importing.py#L12

**Comment by Stwend** [comment]
Hi @PKeidel ,
I replaced the backslashes with forward slashes. Turns out that works for Windows, too - could you do me a favor and download the current repo as a zip to see if the paths work for you now before I close the issue?

**Comment by SBCV** [comment]
next time just use 
```
import os
os.path.join('MeshroomCache', 'Texturing')
```

This will use the path separator of the corresponding operating system

**Comment by PKeidel** [comment]
@Stwend Hi, the current master is working on linux, thank you.
